### ISSUE TITLE
Missing starter 2022 deck lists

### ISSUE THREAD

**Issue by drewmullen** [taw/mtg#2]
related: https://github.com/taw/magic-search-engine/issues/161#issuecomment-1384518990

https://magic.wizards.com/en/news/announcements/magic-the-gathering-2022-starter-kit

apologies, couldn't figure it out in a reasonable amount of time. decklists appear to be embedded in the html of the page so there is no "download url" per-se

deck 1 button:
![image](https://user-images.githubusercontent.com/3812162/212777801-145ab2cb-334e-459f-9af2-8fec0428dd8f.png)

deck 2 button: 
![image](https://user-images.githubusercontent.com/3812162/212777824-cfb231f9-33b8-494b-8865-ac148e0a6f62.png)

**Comment by taw** [comment]
url2txt can handle this. If you have a system that can run it (OSX and Linux out of the box, on Windows you'd need to install ruby somehow), it's this easy:

```
$ bin/url2txt https://magic.wizards.com/en/news/announcements/magic-the-gathering-2022-starter-kit
$ ls *.txt
Red-Green Starter Deck.txt
White-Blue Starter Deck.txt
$ cat Red-Green\ Starter\ Deck.txt
// NAME: Red-Green Starter Deck
// SOURCE: https://magic.wizards.com/en/news/announcements/magic-the-gathering-2022-starter-kit
1 Thundering Raiju
1 Ascendant Packleader
1 Creepy Puppeteer
1 Topiary Stomper
1 Glorious Sunrise
2 Voldaren Stinger
4 Timberland Guide
3 Lambholt Harrier
3 High-Rise Sawjack
3 Spore Crawler
3 Mounted Dreadknight
2 Flourishing Hunter
3 Witch's Web
3 Abrade
2 Burn the Accursed
4 Rugged Highlands
12 Mountain
11 Forest

Sideboard
$ cat White-Blue\ Starter\ Deck.txt
// NAME: White-Blue Starter Deck
// SOURCE: https://magic.wizards.com/en/news/announcements/magic-the-gathering-2022-starter-kit
1 Welcoming Vampire
1 Extraction Specialist
1 Dreamshackle Geist
1 Hullbreaker Horror
1 Consuming Tide
2 Unholy Officiant
3 Backup Agent
4 Wretched Throng
3 Inspiring Overseer
3 Seven-Tail Mentor
2 Stormrider Spirit
2 Nebelgast Beguiler
3 Serpentine Ambush
2 Kill Shot
2 Brute Suit
2 Fading Hope
4 Tranquil Cove
12 Plains
11 Island

Sideboard
```

The repository has all the logic for handling different website's formats.

**Comment by taw** [comment]
It's all done now:

* https://mtg.wtf/deck/snc/red-green-starter-deck
* https://mtg.wtf/deck/snc/white-blue-starter-deck

(attached to SNC as there's no separate mtgjson set for it, and it's the newest set from which it has cards; in the past they were generally attached to core sets)

**Comment by drewmullen** [comment]
hey thanks - i actually did get `url2txt` working locally :D . the confusing part to me was what to do after that. how do the packages coordinate? my assumption was that the process was ... essentially:

1. download the decklist (`url2txt`)
1. generate the json payload for: https://github.com/taw/magic-search-engine/tree/master/data/sets (?)
1. push a PR to update taw/magic-search-engine with the updated json file changes
1. profit

but i think theres more to it than that. if you feel like updating the docs to clarify the process that might be helpful. sorry if im missing something easy here

**Comment by taw** [comment]
> how do the packages coordinate

* use url2txt to get .txt files
* optional: add DATE: annotation if deck release date is not same as set release date
* drop them into right folder in https://github.com/taw/magic-preconstructed-decks, like https://github.com/taw/magic-preconstructed-decks/commit/edc98a1a60dec31ebd6f54b16210fc24851aceed - it's `data/<set type>/<set code>/file.txt`
* PR that

I made url2txt long before I even started this deck database, so I didn't really integrate them.

As it's all plaintext files, you can also make the .txt files in some other way, it's just easier if something tracks annotations automatically.

**Comment by drewmullen** [comment]
cool, ty. i actually found another old deck that isnt represented so ill test this out later

**Comment by taw** [comment]
Yeah, there's probably quite a few decks missing, especially digital-only.
